# version: '3.8'

# services:
#   backend:
#     build:
#       context: ./server
#     container_name: backend
#     ports:
#       - "5000:5000"
#     environment:
#       - NODE_ENV=production
    

#   frontend:
#     build:
#       context: ./client
#     container_name: frontend
#     ports:
#       - "80:80"
#     environment:
#       - NODE_ENV=production
#     depends_on:
#       - backend  


version: '3.8'

services:
  backend:
    build:
      context: ./server
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend